version: '3.7'
services:
  app:
    container_name: joyit_backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      - joyit

networks:
  joyit:
    name: joyit
    driver: bridge
