version: '3.7'
services:
  redis:
    image: redis:7.2
    container_name: joyit_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 10 1 --loglevel warning 
    volumes:
      - ./.docker-conf/data:/data
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - redis

