version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - joyit
    links:
      - redis

networks:
  joyit:
    name: joyit
    driver: bridge
