version: '3.7'
services:
  redis:
    image: redis:7.2
    container_name: joyit_redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 30 1 --loglevel warning
    volumes:
      - ./.docker-conf/data:/data
    networks:
      - joyit


  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - redis
  #   networks:
  #     - joyit
  #   links:
  #     - redis

networks:
  joyit:
    name: joyit
    driver: bridge