version: '3.7'
services:
  redis:
    image: redis:7.2
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 10 1 --loglevel warning 
    volumes:
      - ./.docker-conf/data:/data
    
